### ISSUE TITLE
Tìm hiểu nhập dữ liệu lên Label Studio

### ISSUE THREAD

**Issue by nguyenthanhphuongthao** [nguyenthanhphuongthao/G11_LabelStudio#11]

**Comment by NguyetQue14062002** [comment]
Nội dung "Tìm hiểu nhập dữ liệu lên Label Studio" được trình bày trong Task 10 tài liệu đính kèm:
[20110706_Pham Thi Nguyet Que
](https://docs.google.com/document/d/1bcjliAV6eSqfq09K12x-YLHZilvRSsZvKItO66ePzo8/edit?usp=sharing)
