### ISSUE TITLE
Tìm hiểu cách nhập dữ liệu được chú thích trước vào Label Studio

### ISSUE THREAD

**Issue by nguyenthanhphuongthao** [nguyenthanhphuongthao/G11_LabelStudio#12]

**Comment by HuynhKhoaUTE** [comment]
Tìm hiểu cách nhập dữ liệu được chú thích trước vào Label Studio(https://docs.google.com/document/d/1FEsWGVnC9qgte1ttKKvH9ImkYlBBiD8serIflnTFw0E/edit?usp=sharing)
