### ISSUE TITLE
Tìm hiểu các tag: Rectangle, RectangleLabels, Relation, Relations, Shortcut, Taxonomy, TextArea trong Label Studio

### ISSUE THREAD

**Issue by NguyetQue14062002** [nguyenthanhphuongthao/G11_LabelStudio#20]

**Comment by nguyenthanhphuongthao** [comment]
Nội dung "Tìm hiểu các tag: Rectangle, RectangleLabels, Relation, Relations, Shortcut, Taxonomy, TextArea trong Label Studio" được trình bày trong Task 20 của tài liệu:
[Nguyễn Thanh Phương Thảo - 20110197 - Milestone Tìm hiểu đề tài, setup code/framework](https://docs.google.com/document/d/1BNtwKWENt10RgLJubU7gKTWtej69T2tFvHm_deM_u3E/edit?usp=sharing)
